import { PublicShell } from './components/SiteChrome.js';

export function SourcePolicyPage() {
  return <PublicShell current="source-policy" skip="Skip to source policy"><main id="main-content" tabIndex={-1} className="content-page policy-page">
    <p className="eyebrow">Evidence standards</p>
    <h1>Source policy</h1>
    <p className="page-lede">The tracker is useful only when every incident is grounded in inspectable sources. These rules keep documented findings separate from credible but incomplete leads.</p>

    <section className="policy-callout"><p className="eyebrow">Two evidence lanes</p><h2>Reported but unverified</h2><p>Reports without a primary record or independent corroboration may appear only in the separate <a href="/reported-unverified">Reported / unverified</a> lane. Each lead identifies the companies involved, explains why verification is incomplete, lists the evidence still needed, and links its sources. Leads never count as documented incidents or move into that count silently.</p><p>Company attribution identifies the camera or data-system provider reported in the evidence. It does not, by itself, allege that the provider directed or endorsed a user’s conduct.</p></section>

    <section><p className="eyebrow">01 / Source hierarchy</p><h2>Start with the strongest record</h2><ol className="policy-levels"><li><strong>Primary sources</strong><span>Court filings, docket records, official audits, public-record releases, government records and statements, contracts, policies, and meeting minutes.</span></li><li><strong>Strong secondary sources</strong><span>Established newsrooms, specialist civil-liberties organizations, and investigative reports grounded in named documents.</span></li><li><strong>Background sources</strong><span>Blog posts, social posts, commentary, vendor pages, and general explainers.</span></li></ol></section>

    <section><p className="eyebrow">02 / Publication gates</p><h2>What “documented” requires</h2><div className="policy-grid"><div><h3>Evidence</h3><p>A verified public incident needs at least one primary source or two independent reliable secondary sources. A single secondary source remains a candidate until corroborated.</p></div><div><h3>Human approval</h3><p>Every public record needs a named, non-automated reviewer, a full review date, and an immutable approval reference tied to that exact incident.</p></div><div><h3>Release approval</h3><p>Approval of incident content and approval of release code are separate gates. Deployment authorization must explicitly include the public-record boundary.</p></div><div><h3>Reliability labels</h3><p>Only court, government, public, or official records qualify as primary. Independent secondary sources must have distinct publishers and source hosts.</p></div></div><details className="policy-technical"><summary>Technical approval requirements</summary><p>Public records require <code>review.approval: human-approved</code>, a non-automation reviewer, a full <code>reviewed_at</code> date, and a unique <code>review.approval_reference</code>. The referenced repository document binds the decision to the incident ID and a SHA-256 digest of the approved content. One approval reference cannot authorize multiple records. Candidates and drafts remain <code>pending</code> with no approval reference.</p></details></section>

    <section><p className="eyebrow">03 / Citation requirements</p><h2>What every source records</h2><ul className="policy-checklist"><li>URL and title</li><li>Publisher</li><li>Publication date, when available</li><li>Source type</li><li>Reliability classification</li><li>Claims supported by that exact source</li></ul></section>

    <section><p className="eyebrow">04 / Neutrality and safety</p><h2>Claims stay attached to evidence</h2><ul className="policy-checklist"><li>Attribute allegations to sources.</li><li>Do not publish private personal data unless it is already central to reliable public reporting.</li><li>Mark disputes, corrections, and retractions explicitly.</li><li>Preserve follow-up sources on the canonical incident instead of duplicating it.</li></ul></section>
  </main></PublicShell>;
}
